config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/', to: 'homes#top', as: 'top'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resource :admins, only: [:new, :create]
    resources :words, only: [:show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    resources :words, only: [:show, :new, :create] do
      resource :comments, only: [:create]
      resource :favorites, only: [:create]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :word

  validates :body, presence: true, length: { maximum: 30 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :word
end

app/models/word.rb
class Word < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :body, presence: true, length: { maximum: 50 }

  scope :sort_list, -> {
    {
      "並替え" => "",
      "新着順" => "new",
      "古い順" => "old",
      "いいね順" => "favorites"
    }
  }

  def self.sort(selection)
    case selection
      when 'new'
        order(created_at: :DESC)
      when 'old'
        order(created_at: :ASC)
      when 'favorites'
        left_joins(:favorites).group(:id).order('count(favorites.word_id) desc')
    end
  end
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      redirect_to admin_top_path, notice: '管理者権限を登録しました'
    else
      render :new
    end
  end

  private
    def admin_params
      params.require(:admin).permit(:email, :password, :password_comfirmation)
    end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to request.referer
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin

  def top
    @sort_list = Word.sort_list
    if params[:sort].present?
      @words = Word.sort(params[:sort]).page(params[:page])
    else
      @words = Word.page(params[:page]).order(id: :asc)
    end
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  def new
    @admin = Admin.new
  end

  def create
    admin = Admin.find_by(email: session_params[:email])
    if admin&.authenticate(session_params[:password])
      session[:admin_id] = admin.id
      redirect_to admin_top_path, notice: '管理者権限でログインしました'
    else
      redirect_to admin_login_path, alert: 'ログインできません'
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end

  private
    def session_params
      params.require(:admin).permit(:email, :password)
    end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :authenticate_admin

  def show
    @word = Word.find(params[:id])
  end

  def destroy
    word = Word.find(params[:id])
    word.destroy
    redirect_to admin_top_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_admin

  def authenticate_admin
    if current_admin == nil
      redirect_to admin_login_path, alert: 'ログインが必要です'
    end
  end

 private
   def current_admin
     @current_admin ||= Admin.find_by(id: session[:admin_id]) if session[:admin_id]
   end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admins/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h3>管理サインイン</h3>
  </div>

  <div class="row justify-content-center">
    <div id="message">
      <% if @admin.errors.any? %>
        <% @admin.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center mt-3">
    <table class="table-borderless">
      <%= form_with model: [:admin, @admin], local:true do |f| %>
      <tr>
        <td><%= f.label :email, "メールアドレス" %></td>
        <td><%= f.email_field :email, autocomplete: "email" %></td>
      </tr>
      <tr>
        <td><%= f.label :password, "パスワード" %></td>
        <td><%= f.password_field :password, autocomplete: "current-password" %></td>
      </tr>
      <tr>
        <td><%= f.label :password_confirmation, "パスワード確認用" %></td>
        <td><%= f.password_field :password_confirmation, autocomplete: "new-password" %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= f.submit "サインイン", class: "btn btn-secondary btn-sm" %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h3>投稿一覧</h3>
    <%= form_with method: :get do |f| %>
      <% if @sorted.present? %>
        <%= f.select :sort, @sort_list, selected: @sorted, onChange: "javascript: this.form.submit();" %>
      <% else %>
        <%= f.select :sort, @sort_list, {}, onChange: "javascript: this.form.submit();" %>
      <% end %>
    <% end %>
  </div>

  <div class="row justify-content-center">
    <table class="table table-striped">
      <thead class="text-center">
        <tr>
          <th>ID</th>
          <th>日時</th>
          <th>投稿文</th>
          <th><i class="fas fa-heart fa-fw"></i></th>
          <th><i class="fas fa-comment fa-fw"></i></th>
        </tr>
      </thead>
      <% @words.each do |word| %>
        <tr>
          <td><%= word.id %></td>
          <td>
            <%= link_to admin_word_path(word.id) do %>
              <%= I18n.localize word.created_at %>
            <% end %>
          </td>
          <td><%= word.body %></td>
          <td><%= word.favorites.count %></td>
          <td><%= word.comments.count %></td>
        </tr>
     <% end %>
    </table>
    <%= paginate @words %>
  </div>
</div>

app/views/admin/words/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h3>投稿詳細</h3>

      <table class="table">
        <tr>
          <th style="width: 110px">ID</th>
          <td><%= @word.id %></td>
        </tr>
        <tr>
          <th>日時</th>
          <td><%= I18n.localize @word.created_at %></td>
        </tr>
        <tr>
          <th>投稿文</th>
          <td><%= @word.body %></td>
        </tr>
        <tr>
          <th>いいね数</th>
          <td><%= @word.favorites.count %></td>
        </tr>
        <tr>
          <th>コメント数</th>
          <td><%= @word.comments.count %></td>
        </tr>
        <tr>
          <td>
            <%= link_to "削除", admin_word_path(@word.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
          </td>
          <td></td>
        </tr>
      </table>

      <h4>コメント</h4>
      <table class="table table-striped">
        <% @word.comments.each do |comment| %>
        <tr>
          <td><%= I18n.localize comment.created_at %></td>
          <td><%= comment.body %></td>
          <td><%= link_to "削除", admin_word_comment_path(comment.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fortune</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
        <div class="row justify-content-center">
          <%= image_tag "title.png", class: "title-image" %>
        </div>

        <div class="row justify-content-center mb-3">
          <% if current_admin %>
            <ul>
              <li><%= image_tag "flower-icon-pink.png", class: "nav-image" %></li>
              <li><%= link_to 'Home', root_path %></li>
              <li><%= image_tag "flower-icon-pink.png", class: "nav-image" %></li>
              <li><%= link_to 'Admin Top', admin_top_path %></li>
              <li><%= image_tag "flower-icon-pink.png", class: "nav-image" %></li>
              <li><%= link_to 'Logout', admin_logout_path, method: :delete %></li>
              <li><%= image_tag "flower-icon-pink.png", class: "nav-image" %></li>
          <% else %>
              <li><%= image_tag "flower-icon-blue.png", class: "nav-image" %></li>
              <li><%= link_to root_path do %>Home<% end %></li>
              <li><%= image_tag "flower-icon-blue.png", class: "nav-image" %></li>
              <li><%= link_to about_path do %>About<% end %></li>
              <li><%= image_tag "flower-icon-blue.png", class: "nav-image" %></li>
              <li><%= link_to new_word_path do %>新規投稿<% end %></li>
              <li><%= image_tag "flower-icon-blue.png", class: "nav-image" %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </header>

    <main>
      <div class="container">
        <div class="row justify-content-center mb-2">
          <div id="notice">
            <% if flash[:notice] %>
              <p><%= flash[:notice] %></p>
            <% end %>
          </div>

          <div id="alert">
            <% if flash[:alert] %>
              <p><%= flash[:alert] %></p>
            <% end %>
          </div>
        </div>
      </div>

      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row justify-content-center">
          <% if current_admin %>
            <%= image_tag "flower-icon-pink.png", class: "footer-image" %>
            <%= image_tag "flower-icon-pink.png", class: "footer-image" %>
            <%= image_tag "flower-icon-pink.png", class: "footer-image" %>
            <%= image_tag "flower-icon-pink.png", class: "footer-image" %>
            <%= image_tag "flower-icon-pink.png", class: "footer-image" %>
          <% else %>
            <%= image_tag "flower-icon-blue.png", class: "footer-image" %>
            <%= image_tag "flower-icon-blue.png", class: "footer-image" %>
            <%= image_tag "flower-icon-blue.png", class: "footer-image" %>
            <%= image_tag "flower-icon-blue.png", class: "footer-image" %>
            <%= image_tag "flower-icon-blue.png", class: "footer-image" %>
          <% end %>
        </div>
        <div class="row justify-content-center mb-5">
          <p>© 2021 Today's Happy</p>
        </div>
      </div>
    </footer>
  </body>
</html>